const PDFDocument = require("pdfkit");
const Report = require("../models/Report");

exports.downloadPDF = async (req, res) => {
  try {
    const { reportId, suggestions = [] } = req.body;

    if (!reportId) {
      return res.status(400).json({
        success: false,
        message: "Report ID is required."
      });
    }

    // Find only a report belonging to the logged-in user
    const report = await Report.findOne({
      _id: reportId,
      user: req.user.id
    });

    if (!report) {
      return res.status(404).json({
        success: false,
        message: "Report not found."
      });
    }

    const doc = new PDFDocument({
      margin: 50
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=WebRankAI_Report.pdf"
    );

    doc.pipe(res);

    // =============================
    // Header
    // =============================

    doc
      .fillColor("#2563eb")
      .fontSize(26)
      .text("WebRank AI", {
        align: "center"
      });

    doc
      .fillColor("black")
      .fontSize(18)
      .text("Website Audit Report", {
        align: "center"
      });

    doc.moveDown();

    // =============================
    // Website Information
    // =============================

    doc.fontSize(13);

    doc.text(`Website : ${report.url}`);

    doc.text(
      `Generated : ${new Date().toLocaleString()}`
    );

    doc.moveDown();

    // =============================
    // Overall Score
    // =============================

    const scores = [
      Number(report.performance),
      Number(report.accessibility),
      Number(report.seo),
      Number(report.bestPractices),
      Number(report.pwa)
    ].filter(Number.isFinite);

    const overall = scores.length
      ? Math.round(
          scores.reduce(
            (total, score) => total + score,
            0
          ) / scores.length
        )
      : 0;

    doc
      .fillColor("#16a34a")
      .fontSize(20)
      .text(
        `Overall Score : ${overall}/100`
      );

    doc.moveDown();

    // =============================
    // Audit Scores
    // =============================

    doc
      .fillColor("black")
      .fontSize(16)
      .text("Audit Scores");

    doc.moveDown(0.5);

    doc.fontSize(13);

    doc.text(
      `Performance      : ${report.performance ?? "-"}`
    );

    doc.text(
      `Accessibility    : ${report.accessibility ?? "-"}`
    );

    doc.text(
      `SEO              : ${report.seo ?? "-"}`
    );

    doc.text(
      `Best Practices   : ${report.bestPractices ?? "-"}`
    );

  

    doc.moveDown();

    // =============================
    // AI Recommendations
    // =============================

    doc
      .fillColor("#2563eb")
      .fontSize(18)
      .text("AI Recommendations");

    doc.moveDown();

    if (
      Array.isArray(suggestions) &&
      suggestions.length > 0
    ) {

      suggestions.forEach((item) => {

        doc
          .fillColor("black")
          .fontSize(12)
          .text("• " + String(item));

        doc.moveDown(0.5);

      });

    } else {

      doc
        .fillColor("gray")
        .fontSize(12)
        .text(
          "No AI recommendations available."
        );

    }

    // =============================
    // Footer
    // =============================

    doc.moveDown(2);

    doc
      .fillColor("gray")
      .fontSize(10)
      .text(
        "Generated by WebRank AI",
        {
          align: "center"
        }
      );

    doc.end();

  } catch (error) {

    console.error(
      "PDF GENERATION ERROR:",
      error
    );

    res.status(
      error.name === "CastError" ? 400 : 500
    ).json({
      success: false,
      message: error.message || "Unable to generate PDF."
    });
  }
};